[package]
name = "wrsi"
version = "0.1.0"
authors = ["Gris Ge <cnfourt@gmail.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
wayland-client = "0.26.4"
wayland-commons = "0.26.4"


[build-dependencies]
wayland-scanner = "0.26.4"
